package com.bank.gui;

import com.bank.utils.Toast;
import java.awt.print.PrinterException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moofie
 */
public class PassbookPanel extends javax.swing.JPanel {

    /**
     * Creates new form PassbookPanel
     */
    public PassbookPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaPassbookInfo = new javax.swing.JTextArea();
        btnReset = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Account No.");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 90, 30);
        add(txtAccNo);
        txtAccNo.setBounds(110, 20, 200, 30);

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        add(btnCheck);
        btnCheck.setBounds(313, 20, 110, 30);

        jtaPassbookInfo.setColumns(20);
        jtaPassbookInfo.setRows(5);
        jtaPassbookInfo.setEnabled(false);
        jScrollPane1.setViewportView(jtaPassbookInfo);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 410, 270);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset);
        btnReset.setBounds(10, 340, 140, 30);

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        add(btnPrint);
        btnPrint.setBounds(280, 340, 140, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            // TODO add your handling code here:
            jtaPassbookInfo.print();
        } catch (PrinterException ex) {
            Logger.getLogger(PassbookPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        if(txtAccNo.getText().isEmpty()){
            Toast.makeText(getParent(),"Please enter account number.",Toast.LENGTH_SHORT).display();
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnResetActionPerformed

    
    public void clear(){
        txtAccNo.setText("");
        jtaPassbookInfo.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaPassbookInfo;
    private javax.swing.JTextField txtAccNo;
    // End of variables declaration//GEN-END:variables
}
