package com.bank.gui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moofie
 */
public class RegisterPanel extends javax.swing.JPanel {

    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();

        setLayout(null);

        jLabel1.setText("Firstname");
        add(jLabel1);
        jLabel1.setBounds(20, 10, 150, 30);
        add(jTextField1);
        jTextField1.setBounds(170, 10, 250, 30);
        add(jTextField2);
        jTextField2.setBounds(170, 40, 250, 30);

        jLabel2.setText("Lastname");
        add(jLabel2);
        jLabel2.setBounds(20, 40, 150, 30);

        jLabel3.setText("Gender");
        add(jLabel3);
        jLabel3.setBounds(20, 70, 150, 30);

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        add(jTextField4);
        jTextField4.setBounds(170, 100, 250, 30);

        jLabel4.setText("Address");
        add(jLabel4);
        jLabel4.setBounds(20, 100, 150, 30);

        jRadioButton1.setText("Male");
        add(jRadioButton1);
        jRadioButton1.setBounds(213, 70, 70, 30);

        jRadioButton2.setText("Female");
        add(jRadioButton2);
        jRadioButton2.setBounds(320, 70, 59, 30);

        jLabel5.setText("State");
        add(jLabel5);
        jLabel5.setBounds(20, 130, 150, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        add(jComboBox1);
        jComboBox1.setBounds(170, 130, 250, 30);
        add(jTextField5);
        jTextField5.setBounds(170, 160, 250, 30);

        jLabel6.setText("City");
        add(jLabel6);
        jLabel6.setBounds(20, 160, 150, 30);
        add(jTextField6);
        jTextField6.setBounds(170, 190, 250, 30);

        jLabel7.setText("Postal Code");
        add(jLabel7);
        jLabel7.setBounds(20, 190, 150, 30);
        add(jTextField7);
        jTextField7.setBounds(170, 220, 250, 30);

        jLabel8.setText("Contact Number");
        add(jLabel8);
        jLabel8.setBounds(20, 220, 150, 30);

        jLabel9.setText("Email");
        add(jLabel9);
        jLabel9.setBounds(20, 250, 150, 30);
        add(jTextField8);
        jTextField8.setBounds(170, 250, 250, 30);

        jButton1.setText("Submit");
        add(jButton1);
        jButton1.setBounds(260, 320, 170, 50);

        jButton2.setText("Reset");
        add(jButton2);
        jButton2.setBounds(10, 320, 170, 50);

        jLabel10.setText("Account Type");
        add(jLabel10);
        jLabel10.setBounds(20, 280, 150, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(170, 280, 250, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
