package com.bank.gui;

import com.bank.utils.CommunicationWrapper;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Moofie
 */
public class RegisterPanel extends javax.swing.JPanel {
    private CommunicationWrapper cw;
    /**
     * Creates new form RegisterPanel
     */
    public RegisterPanel(CommunicationWrapper cw) {
        this.cw = cw;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrp = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jrbMale = new javax.swing.JRadioButton();
        jrbFemale = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jcbState = new javax.swing.JComboBox();
        txtCity = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtPostCode = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jcbAccType = new javax.swing.JComboBox();

        setLayout(null);

        jLabel1.setText("Firstname");
        add(jLabel1);
        jLabel1.setBounds(20, 10, 150, 30);
        add(txtFname);
        txtFname.setBounds(170, 10, 250, 30);
        add(txtLname);
        txtLname.setBounds(170, 40, 250, 30);

        jLabel2.setText("Lastname");
        add(jLabel2);
        jLabel2.setBounds(20, 40, 150, 30);

        jLabel3.setText("Gender");
        add(jLabel3);
        jLabel3.setBounds(20, 70, 150, 30);
        add(txtAddress);
        txtAddress.setBounds(170, 100, 250, 30);

        jLabel4.setText("Address");
        add(jLabel4);
        jLabel4.setBounds(20, 100, 150, 30);

        btngrp.add(jrbMale);
        jrbMale.setSelected(true);
        jrbMale.setText("Male");
        add(jrbMale);
        jrbMale.setBounds(213, 70, 70, 30);

        btngrp.add(jrbFemale);
        jrbFemale.setText("Female");
        add(jrbFemale);
        jrbFemale.setBounds(320, 70, 59, 30);

        jLabel5.setText("State");
        add(jLabel5);
        jLabel5.setBounds(20, 130, 150, 30);

        jcbState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Perak", "Selangor", "Seremban", "Melaka", "Wilayah Persekutuan" }));
        add(jcbState);
        jcbState.setBounds(170, 130, 250, 30);
        add(txtCity);
        txtCity.setBounds(170, 160, 250, 30);

        jLabel6.setText("City");
        add(jLabel6);
        jLabel6.setBounds(20, 160, 150, 30);
        add(txtPostCode);
        txtPostCode.setBounds(170, 190, 250, 30);

        jLabel7.setText("Postal Code");
        add(jLabel7);
        jLabel7.setBounds(20, 190, 150, 30);
        add(txtContact);
        txtContact.setBounds(170, 220, 250, 30);

        jLabel8.setText("Contact Number");
        add(jLabel8);
        jLabel8.setBounds(20, 220, 150, 30);

        jLabel9.setText("Email");
        add(jLabel9);
        jLabel9.setBounds(20, 250, 150, 30);
        add(txtEmail);
        txtEmail.setBounds(170, 250, 250, 30);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(260, 320, 170, 50);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset);
        btnReset.setBounds(10, 320, 170, 50);

        jLabel10.setText("Account Type");
        add(jLabel10);
        jLabel10.setBounds(20, 280, 150, 30);

        jcbAccType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Saving", "Current" }));
        add(jcbAccType);
        jcbAccType.setBounds(170, 280, 250, 30);
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
      
            String fname = txtFname.getText().trim();
            String lname = txtLname.getText().trim();
            String gender = "";
            if(jrbMale.isSelected())
                gender = "Male";
            else{
                gender = "Female";
            }
            String addr = txtAddress.getText().trim();
            String state = jcbState.getSelectedItem().toString();
            String city = txtCity.getText().trim();
            String postcode = txtPostCode.getText().trim();
            String contact = txtContact.getText().trim();
            String email =txtEmail.getText().trim();
            String acctype = jcbAccType.getSelectedItem().toString();
        
    }//GEN-LAST:event_btnSubmitActionPerformed
    
    public void clear() {
        txtFname.setText("");
        txtLname.setText("");
        jrbMale.setSelected(true);        
        txtAddress.setText("");
        jcbState.setSelectedIndex(0);
        txtCity.setText("");        
        txtPostCode.setText("");
        txtContact.setText("");
        txtEmail.setText("");
        jcbAccType.setSelectedIndex(0);
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.ButtonGroup btngrp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox jcbAccType;
    private javax.swing.JComboBox jcbState;
    private javax.swing.JRadioButton jrbFemale;
    private javax.swing.JRadioButton jrbMale;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtPostCode;
    // End of variables declaration//GEN-END:variables
}
