package com.bank.gui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moofie
 */
public class WithdrawPanel extends javax.swing.JPanel {

    /**
     * Creates new form WithdrawPanel
     */
    public WithdrawPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(440, 380));
        setLayout(null);

        jLabel1.setText("Account Number ");
        add(jLabel1);
        jLabel1.setBounds(20, 60, 390, 30);
        add(jTextField1);
        jTextField1.setBounds(20, 90, 390, 30);

        jLabel2.setText("IC Number");
        add(jLabel2);
        jLabel2.setBounds(20, 130, 220, 30);
        add(jTextField2);
        jTextField2.setBounds(20, 160, 390, 30);

        jLabel3.setText("Amount to Withdraw");
        add(jLabel3);
        jLabel3.setBounds(20, 200, 180, 30);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        add(jTextField3);
        jTextField3.setBounds(20, 230, 390, 30);

        jButton1.setText("Submit");
        add(jButton1);
        jButton1.setBounds(260, 320, 170, 50);

        jButton2.setText("Reset");
        add(jButton2);
        jButton2.setBounds(10, 320, 170, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
