package com.bank.gui;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moofie
 */
public class LoanPanel extends javax.swing.JPanel {

    /**
     * Creates new form LoanPanel
     */
    public LoanPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Loan Type");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 140, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox1);
        jComboBox1.setBounds(160, 20, 260, 30);

        jLabel2.setText("Loan Amount");
        add(jLabel2);
        jLabel2.setBounds(20, 60, 140, 30);
        add(jTextField1);
        jTextField1.setBounds(160, 60, 260, 30);

        jLabel3.setText("Loan Interest Rate");
        add(jLabel3);
        jLabel3.setBounds(20, 100, 140, 30);
        add(jTextField2);
        jTextField2.setBounds(160, 100, 260, 30);

        jLabel4.setText("Duration");
        add(jLabel4);
        jLabel4.setBounds(20, 140, 140, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(jComboBox2);
        jComboBox2.setBounds(160, 140, 260, 30);

        jLabel5.setText("Loaner Name");
        add(jLabel5);
        jLabel5.setBounds(20, 180, 140, 30);
        add(jTextField3);
        jTextField3.setBounds(160, 180, 260, 30);

        jLabel6.setText("Loaner IC Number");
        add(jLabel6);
        jLabel6.setBounds(20, 220, 140, 30);
        add(jTextField4);
        jTextField4.setBounds(160, 220, 260, 30);

        jLabel7.setText("Loaner Contact No");
        add(jLabel7);
        jLabel7.setBounds(20, 260, 140, 30);
        add(jTextField5);
        jTextField5.setBounds(160, 260, 260, 30);

        jButton2.setText("Reset");
        add(jButton2);
        jButton2.setBounds(10, 320, 170, 50);

        jButton1.setText("Submit");
        add(jButton1);
        jButton1.setBounds(260, 320, 170, 50);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
