package com.bank.gui;


import com.bank.entity.Branch;
import com.bank.entity.MySQLConnection;
import com.bank.server.BankServerFrame;
import com.bank.utils.CommunicationWrapper;
import com.bank.utils.Toast;
import java.awt.CardLayout;
import java.net.SocketException;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moofie
 */
public class Main extends javax.swing.JFrame {
    private CardLayout cl;
    private CommunicationWrapper cw;
    private DefaultComboBoxModel dcbmBranch;
    private Branch branch;
    private JComboBox jcb;
    private String branchCode;
    /**
     * Creates new form Main
     */
    public Main() {
        
        jcb = new JComboBox();
        populateBranchCode();
        JOptionPane.showMessageDialog(null, jcb, "Select Option", JOptionPane.QUESTION_MESSAGE);
        branchCode = jcb.getSelectedItem().toString();
        
        try{
            cw = new CommunicationWrapper(5500);
        } catch (SocketException ex) {
            System.out.println("Unable to open socket : " + ex.getMessage());
            System.out.println("Closing server..");
            try {
                Thread.sleep(2000);
                System.exit(1);
            } catch (InterruptedException ex1) {
            }
        }
        initComponents();
        jpMainCard.add(new WithdrawPanel(cw,branchCode), "withdraw");
        jpMainCard.add(new DepositPanel(cw,branchCode), "deposit");
        jpMainCard.add(new TransferPanel(cw,branchCode), "transfer");
        jpMainCard.add(new RegisterPanel(cw,branchCode), "register");
        jpMainCard.add(new LoanPanel(cw,branchCode), "loan");
        jpMainCard.add(new PassbookPanel(cw,branchCode), "passbook");
        cl = (CardLayout) jpMainCard.getLayout();
        
    }
     private void populateBranchCode() {
        dcbmBranch = new DefaultComboBoxModel();
        Branch branch = new Branch();
        ArrayList<String> d = branch.obtainAllBranchCode(MySQLConnection.getConnection());
        if (!d.isEmpty()) {
            for (int i = 0; i < d.size(); i++) {
                dcbmBranch.addElement(d.get(i));
            }
            jcb.setModel(dcbmBranch);
        } else {
            Toast.makeText(Main.this, "No branch found.", Toast.LENGTH_SHORT).display();
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtWithdraw = new javax.swing.JButton();
        jbtDeposit = new javax.swing.JButton();
        jbtTransfer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jbtRegister = new javax.swing.JButton();
        jbtLoan = new javax.swing.JButton();
        jbtUpdate = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jpMainCard = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jbtWithdraw.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b.png"))); // NOI18N
        jbtWithdraw.setText("Withdraw");
        jbtWithdraw.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtWithdraw.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtWithdraw.setIconTextGap(0);
        jbtWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtWithdrawActionPerformed(evt);
            }
        });
        jPanel1.add(jbtWithdraw);
        jbtWithdraw.setBounds(10, 70, 120, 50);

        jbtDeposit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/a.jpg"))); // NOI18N
        jbtDeposit.setText("Deposit");
        jbtDeposit.setIconTextGap(6);
        jbtDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDepositActionPerformed(evt);
            }
        });
        jPanel1.add(jbtDeposit);
        jbtDeposit.setBounds(10, 130, 120, 50);

        jbtTransfer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/c.png"))); // NOI18N
        jbtTransfer.setText("Transfer");
        jbtTransfer.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtTransfer.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTransferActionPerformed(evt);
            }
        });
        jPanel1.add(jbtTransfer);
        jbtTransfer.setBounds(10, 190, 120, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Ong Ong Lai Banking System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 570, 60);

        jbtRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/f.jpg"))); // NOI18N
        jbtRegister.setText("Register");
        jbtRegister.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtRegister.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jbtRegister);
        jbtRegister.setBounds(10, 250, 120, 50);

        jbtLoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/e.png"))); // NOI18N
        jbtLoan.setText("Loan");
        jbtLoan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtLoan.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLoanActionPerformed(evt);
            }
        });
        jPanel1.add(jbtLoan);
        jbtLoan.setBounds(10, 310, 120, 50);

        jbtUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/d.jpg"))); // NOI18N
        jbtUpdate.setText("<html>Update<br/> passbook");
        jbtUpdate.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbtUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtUpdate);
        jbtUpdate.setBounds(10, 370, 120, 50);

        jpMainCard.setPreferredSize(new java.awt.Dimension(440, 380));
        jpMainCard.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpMainCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jpMainCard, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(130, 70, 440, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtWithdrawActionPerformed
        cl.show(jpMainCard, "withdraw");
    }//GEN-LAST:event_jbtWithdrawActionPerformed

    private void jbtDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDepositActionPerformed
        cl.show(jpMainCard, "deposit");
    }//GEN-LAST:event_jbtDepositActionPerformed

    private void jbtTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTransferActionPerformed
        cl.show(jpMainCard, "transfer");
    }//GEN-LAST:event_jbtTransferActionPerformed

    private void jbtRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegisterActionPerformed
        cl.show(jpMainCard, "register");
    }//GEN-LAST:event_jbtRegisterActionPerformed

    private void jbtLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLoanActionPerformed
        cl.show(jpMainCard, "loan");
    }//GEN-LAST:event_jbtLoanActionPerformed

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
        cl.show(jpMainCard, "passbook");
    }//GEN-LAST:event_jbtUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtDeposit;
    private javax.swing.JButton jbtLoan;
    private javax.swing.JButton jbtRegister;
    private javax.swing.JButton jbtTransfer;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JButton jbtWithdraw;
    private javax.swing.JPanel jpMainCard;
    // End of variables declaration//GEN-END:variables
}
