package com.bank.gui;


import com.bank.utils.CommunicationWrapper;
import java.awt.CardLayout;
import java.net.SocketException;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Moofie
 */
public class Main extends javax.swing.JFrame {
    private CardLayout cl;
    private CommunicationWrapper cw;
    /**
     * Creates new form Main
     */
    public Main() {
        try{
            cw = new CommunicationWrapper(5000);
        } catch (SocketException ex) {
            System.out.println("Unable to open socket : " + ex.getMessage());
            System.out.println("Closing server..");
            try {
                Thread.sleep(2000);
                System.exit(1);
            } catch (InterruptedException ex1) {
            }
        }
        initComponents();
        jpMainCard.add(new WithdrawPanel(cw), "withdraw");
        jpMainCard.add(new DepositPanel(cw), "deposit");
        jpMainCard.add(new TransferPanel(cw), "transfer");
        jpMainCard.add(new RegisterPanel(cw), "register");
        jpMainCard.add(new LoanPanel(cw), "loan");
        jpMainCard.add(new PassbookPanel(cw), "passbook");
        cl = (CardLayout) jpMainCard.getLayout();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtWithdraw = new javax.swing.JButton();
        jbtDeposit = new javax.swing.JButton();
        jbtTransfer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jpMainCard = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jbtRegister = new javax.swing.JButton();
        jbtLoan = new javax.swing.JButton();
        jbtUpdate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jbtWithdraw.setText("Withdraw");
        jbtWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtWithdrawActionPerformed(evt);
            }
        });
        jPanel1.add(jbtWithdraw);
        jbtWithdraw.setBounds(20, 70, 90, 50);

        jbtDeposit.setText("Deposit");
        jbtDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtDepositActionPerformed(evt);
            }
        });
        jPanel1.add(jbtDeposit);
        jbtDeposit.setBounds(20, 130, 90, 50);

        jbtTransfer.setText("Transfer");
        jbtTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtTransferActionPerformed(evt);
            }
        });
        jPanel1.add(jbtTransfer);
        jbtTransfer.setBounds(20, 190, 90, 50);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FF8 Banking System");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 560, 60);

        jpMainCard.setPreferredSize(new java.awt.Dimension(440, 380));
        jpMainCard.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
        );

        jpMainCard.add(jPanel2, "null");

        jPanel1.add(jpMainCard);
        jpMainCard.setBounds(120, 70, 440, 380);

        jbtRegister.setText("Register");
        jbtRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(jbtRegister);
        jbtRegister.setBounds(20, 250, 90, 50);

        jbtLoan.setText("Loan");
        jbtLoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLoanActionPerformed(evt);
            }
        });
        jPanel1.add(jbtLoan);
        jbtLoan.setBounds(20, 310, 90, 50);

        jbtUpdate.setText("<html>Update<br/> passbook");
        jbtUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(jbtUpdate);
        jbtUpdate.setBounds(20, 370, 90, 50);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtWithdrawActionPerformed
        cl.show(jpMainCard, "withdraw");
    }//GEN-LAST:event_jbtWithdrawActionPerformed

    private void jbtDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtDepositActionPerformed
        cl.show(jpMainCard, "deposit");
    }//GEN-LAST:event_jbtDepositActionPerformed

    private void jbtTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtTransferActionPerformed
        cl.show(jpMainCard, "transfer");
    }//GEN-LAST:event_jbtTransferActionPerformed

    private void jbtRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtRegisterActionPerformed
        cl.show(jpMainCard, "register");
    }//GEN-LAST:event_jbtRegisterActionPerformed

    private void jbtLoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLoanActionPerformed
        cl.show(jpMainCard, "loan");
    }//GEN-LAST:event_jbtLoanActionPerformed

    private void jbtUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtUpdateActionPerformed
        cl.show(jpMainCard, "passbook");
    }//GEN-LAST:event_jbtUpdateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbtDeposit;
    private javax.swing.JButton jbtLoan;
    private javax.swing.JButton jbtRegister;
    private javax.swing.JButton jbtTransfer;
    private javax.swing.JButton jbtUpdate;
    private javax.swing.JButton jbtWithdraw;
    private javax.swing.JPanel jpMainCard;
    // End of variables declaration//GEN-END:variables
}
