package com.bank.gui;

import com.bank.utils.CommunicationWrapper;
import com.bank.utils.CustomScrollBarUI;
import com.bank.utils.Operation;
import com.bank.utils.TextFieldLimiter;
import com.bank.utils.Toast;
import java.awt.print.PrinterException;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.text.AbstractDocument;
import org.json.JSONArray;
import org.json.JSONException;
import org.json.JSONObject;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Moofie
 */
public class PassbookPanel extends javax.swing.JPanel {

    private CommunicationWrapper cw;
    private String branchCode;
    private int portNo;

    /**
     * Creates new form PassbookPanel
     */
    public PassbookPanel(CommunicationWrapper cw, String branchCode, int portNo) {
        this.cw = cw;
        this.branchCode = branchCode;
        this.portNo = portNo;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtaPassbookInfo = new javax.swing.JTextArea();
        btnReset = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Account No.");
        add(jLabel1);
        jLabel1.setBounds(20, 20, 90, 30);

        AbstractDocument aDocAcc = (AbstractDocument)txtAccNo.getDocument();
        aDocAcc.setDocumentFilter(new TextFieldLimiter("\\d{0,14}"));
        add(txtAccNo);
        txtAccNo.setBounds(110, 20, 200, 30);

        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        add(btnCheck);
        btnCheck.setBounds(313, 20, 110, 30);

        jScrollPane1.getVerticalScrollBar().setUI(new CustomScrollBarUI());

        jtaPassbookInfo.setEditable(false);
        jtaPassbookInfo.setColumns(20);
        jtaPassbookInfo.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        jtaPassbookInfo.setRows(5);
        jtaPassbookInfo.setEnabled(false);
        jScrollPane1.setViewportView(jtaPassbookInfo);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 410, 270);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset);
        btnReset.setBounds(10, 340, 140, 30);

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        add(btnPrint);
        btnPrint.setBounds(280, 340, 140, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        try {
            // TODO add your handling code here:
            jtaPassbookInfo.print();
        } catch (PrinterException ex) {
            Logger.getLogger(PassbookPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        if (txtAccNo.getText().isEmpty()) {
            Toast.makeText(getParent(), "Please enter account number.", Toast.LENGTH_SHORT).display();
        } else {
            jtaPassbookInfo.setEnabled(true);
            try {
                JSONObject j = new JSONObject();
                j.put("operation", Operation.TRANSACTION);
                JSONObject content = new JSONObject();
                content.put("accno", txtAccNo.getText());
                content.put("port", this.portNo);
                content.put("bCode", this.branchCode);
                content.put("address", InetAddress.getLocalHost().getHostAddress());
                j.put("content", content);
                cw.send(j, InetAddress.getLocalHost(), 5000);
                JSONObject result = cw.receive();
                generateTransactionLog(result);
            } catch (JSONException | UnknownHostException ex) {
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_btnResetActionPerformed

    private void generateTransactionLog(JSONObject json) {
        try {
            if (json.getBoolean("record")) {
                JSONArray jsArr = json.getJSONObject("content").getJSONArray("result");
                jtaPassbookInfo.setText("#   Transaction Date    Transaction Type      Amount\n");
                jtaPassbookInfo.append("========================================================\n");
                for (int i = 0; i < jsArr.length(); i++) {
                    JSONObject temp = jsArr.getJSONObject(i);
                    String line =
                            String.format("%-6d%-22s%-16sRM%9.2f", i + 1, temp.getString("transactionDate"),
                            (temp.getString("transactionType").equals("CRD") ? "Credit" : "Debit"),
                            temp.getDouble("amount"));
                    jtaPassbookInfo.append(line + "\n");
                }
            } else {
                jtaPassbookInfo.setText("No record found, did you enter the correct account number?");
            }
        } catch (JSONException ex) {
            ex.printStackTrace();
        }
    }

    public void clear() {
        txtAccNo.setText("");
        jtaPassbookInfo.setText("");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnReset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jtaPassbookInfo;
    private javax.swing.JTextField txtAccNo;
    // End of variables declaration//GEN-END:variables
}
