package com.bank.gui;

import com.bank.utils.CommunicationWrapper;
import com.bank.utils.Operation;
import com.bank.utils.Toast;
import java.net.InetAddress;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.json.JSONException;
import org.json.JSONObject;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Moofie
 */
public class TransferPanel extends javax.swing.JPanel {

    private CommunicationWrapper cw;
    private String branchCode;

    /**
     * Creates new form TransferPanel
     */
    public TransferPanel(CommunicationWrapper cw, String branchCode) {
        this.cw = cw;
        this.branchCode = branchCode;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtAccNo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtAccNoReceiver = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAmountTransfer = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setText("Account Number");
        add(jLabel1);
        jLabel1.setBounds(20, 60, 190, 30);
        add(txtAccNo);
        txtAccNo.setBounds(20, 90, 390, 30);

        jLabel2.setText("Beneficial Account Number ");
        add(jLabel2);
        jLabel2.setBounds(20, 130, 220, 30);
        add(txtAccNoReceiver);
        txtAccNoReceiver.setBounds(20, 160, 390, 30);

        jLabel3.setText("Amount to Transfer");
        add(jLabel3);
        jLabel3.setBounds(20, 200, 180, 30);
        add(txtAmountTransfer);
        txtAmountTransfer.setBounds(20, 230, 390, 30);

        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        add(btnReset);
        btnReset.setBounds(10, 320, 170, 50);

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        add(btnSubmit);
        btnSubmit.setBounds(260, 320, 170, 50);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        Double amount=0.00;
        String accNo = txtAccNo.getText().trim();
        String accReceiver = txtAccNoReceiver.getText().trim();
        try {
            amount = Double.parseDouble(txtAmountTransfer.getText().trim());
        } catch (NumberFormatException ex) {
            Toast.makeText(getParent(), "Please enter amount in number format.", Toast.LENGTH_SHORT).display();
        }

        try {

            JSONObject j = new JSONObject();
            j.put("operation", Operation.TRANSFER);
            JSONObject content = new JSONObject();
            content.put("accNo",accNo);
            content.put("accReceiver", accReceiver);
            content.put("amount", amount);
            content.put("port", 5500);
            content.put("bCode", this.branchCode);
            content.put("address", InetAddress.getLocalHost().getHostAddress());
            j.put("content", content);
            cw.send(j, InetAddress.getLocalHost(), 5000);
            JSONObject js = cw.receive();
            System.out.println(js.toString());
        } catch (JSONException ex) {
            ex.printStackTrace();
            System.out.println(ex);
        } catch (UnknownHostException ex) {
            Logger.getLogger(TransferPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtAccNo.setText("");
        txtAccNoReceiver.setText("");
        txtAmountTransfer.setText("");
    }//GEN-LAST:event_btnResetActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtAccNo;
    private javax.swing.JTextField txtAccNoReceiver;
    private javax.swing.JTextField txtAmountTransfer;
    // End of variables declaration//GEN-END:variables
}
